server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # API proxy - kubectl proxy'ye yönlendirir
  location /k8s-api/ {
    proxy_pass http://localhost:8001/;
    proxy_set_header Host $host;
  }

  gzip on;
  gzip_types text/plain text/css application/json application/javascript;
}
