export const DEMO = {
  nodes: [
    { id: "node-cluster-node-a", kind: "Node", name: "cluster-node-a", namespace: "cluster", status: "Ready", nodeReady: true, nodeRoles: ["worker"], podCount: 5 },
    { id: "node-cluster-node-b", kind: "Node", name: "cluster-node-b", namespace: "cluster", status: "MemoryPressure", nodeReady: true, nodeRoles: ["worker"], podCount: 4, nodePressure: [{ type: "MemoryPressure", status: true }] },
    { id: "ing-web", kind: "Ingress", name: "web-ingress", namespace: "production", status: "Active" },
    { id: "svc-fe", kind: "Service", name: "frontend-svc", namespace: "production", status: "Active" },
    { id: "svc-api", kind: "Service", name: "api-svc", namespace: "production", status: "Active" },
    { id: "svc-db", kind: "Service", name: "db-svc", namespace: "production", status: "Active" },
    { id: "dep-fe", kind: "Deployment", name: "frontend", namespace: "production", status: "3/3" },
    { id: "dep-api", kind: "Deployment", name: "api-server", namespace: "production", status: "1/3" },
    { id: "sts-db", kind: "StatefulSet", name: "postgres", namespace: "production", status: "1/1" },
    { id: "pod-f1", kind: "Pod", name: "frontend-x7k2p", namespace: "production", status: "Running", cpuPercent: 45, memPercent: 52, restarts: 0, nodeName: "cluster-node-a",
      podContainers: ["app"], podImageInfo: "app: demo/app:v2.4.1", sampleLog: "2026-03-23T10:00:01.123Z [demo] GET /health 200 2ms\n2026-03-23T10:00:11.456Z [demo] GET /api/ready 200 4ms" },
    { id: "pod-f2", kind: "Pod", name: "frontend-m9n3q", namespace: "production", status: "Running", cpuPercent: 38, memPercent: 48, restarts: 1, nodeName: "cluster-node-a" },
    { id: "pod-f3", kind: "Pod", name: "frontend-p4r8s", namespace: "production", status: "Running", cpuPercent: 92, memPercent: 61, restarts: 0, nodeName: "cluster-node-b" },
    { id: "pod-a1", kind: "Pod", name: "api-server-a2b3", namespace: "production", status: "CrashLoopBackOff", cpuPercent: 12, memPercent: 18, restarts: 14, nodeName: "cluster-node-b" },
    { id: "pod-a2", kind: "Pod", name: "api-server-c4d5", namespace: "production", status: "Pending", cpuPercent: 0, memPercent: 0, restarts: 0 },
    { id: "pod-a3", kind: "Pod", name: "api-server-e6f7", namespace: "production", status: "Running", cpuPercent: 55, memPercent: 77, restarts: 2, nodeName: "cluster-node-a" },
    { id: "pod-db", kind: "Pod", name: "postgres-0", namespace: "production", status: "Running", cpuPercent: 62, memPercent: 88, restarts: 0, nodeName: "cluster-node-b" },
    { id: "cm-app", kind: "ConfigMap", name: "app-config", namespace: "production", status: "Active" },
    { id: "cm-nginx", kind: "ConfigMap", name: "nginx-config", namespace: "production", status: "Active" },
    { id: "sec-tls", kind: "Secret", name: "tls-secret", namespace: "production", status: "Active" },
    { id: "pvc-db", kind: "PersistentVolumeClaim", name: "postgres-data", namespace: "production", status: "Bound" },
    { id: "dep-cache", kind: "Deployment", name: "redis-cache", namespace: "production", status: "0/2" },
    { id: "svc-cache", kind: "Service", name: "redis-svc", namespace: "production", status: "Active" },
    { id: "pod-c1", kind: "Pod", name: "redis-0", namespace: "production", status: "OOMKilled", cpuPercent: 88, memPercent: 98, restarts: 7, nodeName: "cluster-node-b" },
    { id: "pod-c2", kind: "Pod", name: "redis-1", namespace: "production", status: "Evicted", cpuPercent: 0, memPercent: 0, restarts: 0, nodeName: "cluster-node-b" },
    { id: "dep-prom", kind: "Deployment", name: "prometheus", namespace: "monitoring", status: "1/1" },
    { id: "svc-prom", kind: "Service", name: "prometheus-svc", namespace: "monitoring", status: "Active" },
    { id: "pod-prom", kind: "Pod", name: "prometheus-9x8y", namespace: "monitoring", status: "Running", cpuPercent: 22, memPercent: 41, restarts: 0, nodeName: "cluster-node-a" },
    { id: "dep-graf", kind: "Deployment", name: "grafana", namespace: "monitoring", status: "1/1" },
    { id: "svc-graf", kind: "Service", name: "grafana-svc", namespace: "monitoring", status: "Active" },
    { id: "pod-graf", kind: "Pod", name: "grafana-a1b2c3", namespace: "monitoring", status: "Running", cpuPercent: 14, memPercent: 33, restarts: 0, nodeName: "cluster-node-a" },
    { id: "cm-prom", kind: "ConfigMap", name: "prometheus-config", namespace: "monitoring", status: "Active" },
    { id: "svc-old", kind: "Service", name: "legacy-svc", namespace: "production", status: "Active" },
  ],
  edges: [
    { id: "e1", source: "ing-web", target: "svc-fe", type: "routes", label: "/" },
    { id: "e2", source: "ing-web", target: "svc-api", type: "routes", label: "/api" },
    { id: "e3", source: "svc-fe", target: "pod-f1", type: "selects" },
    { id: "e4", source: "svc-fe", target: "pod-f2", type: "selects" },
    { id: "e5", source: "svc-fe", target: "pod-f3", type: "selects" },
    { id: "e6", source: "svc-api", target: "pod-a1", type: "selects" },
    { id: "e7", source: "svc-api", target: "pod-a2", type: "selects" },
    { id: "e8", source: "svc-api", target: "pod-a3", type: "selects" },
    { id: "e9", source: "svc-db", target: "pod-db", type: "selects" },
    { id: "e10", source: "dep-fe", target: "pod-f1", type: "owns" },
    { id: "e11", source: "dep-fe", target: "pod-f2", type: "owns" },
    { id: "e12", source: "dep-fe", target: "pod-f3", type: "owns" },
    { id: "e13", source: "dep-api", target: "pod-a1", type: "owns" },
    { id: "e14", source: "dep-api", target: "pod-a2", type: "owns" },
    { id: "e15", source: "dep-api", target: "pod-a3", type: "owns" },
    { id: "e16", source: "sts-db", target: "pod-db", type: "owns" },
    { id: "e17", source: "dep-api", target: "cm-app", type: "uses" },
    { id: "e18", source: "dep-fe", target: "cm-nginx", type: "uses" },
    { id: "e19", source: "ing-web", target: "sec-tls", type: "uses" },
    { id: "e20", source: "sts-db", target: "pvc-db", type: "uses" },
    { id: "e21", source: "dep-api", target: "svc-db", type: "calls" },
    { id: "e22", source: "dep-api", target: "svc-cache", type: "calls" },
    { id: "e23", source: "dep-cache", target: "pod-c1", type: "owns" },
    { id: "e24", source: "dep-cache", target: "pod-c2", type: "owns" },
    { id: "e25", source: "svc-cache", target: "pod-c1", type: "selects" },
    { id: "e26", source: "svc-cache", target: "pod-c2", type: "selects" },
    { id: "e27", source: "dep-prom", target: "pod-prom", type: "owns" },
    { id: "e28", source: "dep-graf", target: "pod-graf", type: "owns" },
    { id: "e29", source: "svc-prom", target: "pod-prom", type: "selects" },
    { id: "e30", source: "svc-graf", target: "pod-graf", type: "selects" },
    { id: "e31", source: "dep-prom", target: "cm-prom", type: "uses" },
    { id: "e32", source: "dep-graf", target: "svc-prom", type: "calls" },
    { id: "e33", source: "node-cluster-node-a", target: "pod-f1", type: "hosts" },
    { id: "e34", source: "node-cluster-node-a", target: "pod-f2", type: "hosts" },
    { id: "e35", source: "node-cluster-node-a", target: "pod-a3", type: "hosts" },
    { id: "e36", source: "node-cluster-node-a", target: "pod-prom", type: "hosts" },
    { id: "e37", source: "node-cluster-node-a", target: "pod-graf", type: "hosts" },
    { id: "e38", source: "node-cluster-node-b", target: "pod-f3", type: "hosts" },
    { id: "e39", source: "node-cluster-node-b", target: "pod-a1", type: "hosts" },
    { id: "e40", source: "node-cluster-node-b", target: "pod-db", type: "hosts" },
    { id: "e41", source: "node-cluster-node-b", target: "pod-c1", type: "hosts" },
    { id: "e42", source: "node-cluster-node-b", target: "pod-c2", type: "hosts" },
  ],
};
